Support Thermo3 and Expand2 Clickboards
devolo/dlan-greenphy-sdk pull request #1
Opened 2017-08-09 13:55 UTC by cdomnik

Information
------------------------------------------------------------
Added Task for Thermo3Click and Expand2Click.
Adapt Weblayout to view the generated data.
------------------------------------------------------------

Bilder
--------------------------------------------------------------------------------------------------------------------
![screenshot_thermo3](https://user-images.githubusercontent.com/30650575/29125012-d6222a66-7d1a-11e7-9931-a27515503619.png)
--------------------------------------------------------------------------------------------------------------------
![screenshot_expand2](https://user-images.githubusercontent.com/30650575/29125015-dd375efc-7d1a-11e7-959e-09beef4df46a.png)

2017-08-09 17:21 UTC, mlamberti commented on Applications/Clickboards/src/Expand2Click.c
> +		//toggle obits each time the Task is called
Why don't toggle both bits in one go, without 'swap'?
oBits ^= 0x03;

2017-08-09 18:48 UTC, mlamberti requested changes
Hey Christoph,
ich habe deine Änderungen durchgesehen und noch ein paar Bugs gefunden bzw. Bemerkungen geschrieben. Kannst du die Sachen bitte noch ändern?
Danke, Michael

2017-08-09 18:48 UTC, mlamberti commented on Applications/Clickboards/src/Expand2Click.c
> +						 xClickTaskHandleExpand )
xTaskCreate requires a pointer to a TaskHandle_t, thus line 187:
`&xClickTaskHandleExpand )`

2017-08-09 18:48 UTC, mlamberti commented on Applications/Clickboards/src/thermo3click.c
> +						 xClickTaskHandleThermo )
Same as above, should be a pointer: `&xClickTaskHandleThermo`

2017-08-09 18:48 UTC, mlamberti commented on Applications/HTTP/httpd-fs/main.js
> +        			<td>H&oumlchste Temperatur</td>
I'm not sure wether it's necessary to escape HTML entities, but it must be `&ouml;`

2017-08-09 18:48 UTC, mlamberti commented on Applications/HTTP/httpd-fs/main.js
> +        			<td>H&oumlchste Temperatur</td>
Also `&deg;C`

2017-08-09 18:48 UTC, mlamberti commented on Applications/HTTP/httpd-fs/main.js
> +        	not jet implemented
yet

2017-08-09 18:48 UTC, mlamberti commented on Applications/HTTP/httpd-fs/main.js
> +        				<td>Gez&aumlhlte Wassermenge seit Reset</td>
`&auml;`

2017-08-09 18:48 UTC, mlamberti commented on Applications/HTTP/httpd-fs/main.js
> +  	xhr = $.getJSON('http://192.168.1.118/' + 'status.json?action=set&led=' + ($('#led-switch').is(":checked") ? 'on' : 'off'), function(json) {});
The URI used for testing purposes shouldn't be part of the pull request.

2017-08-09 18:48 UTC, mlamberti commented on Applications/HTTP/httpd-fs/main.js
> +			var checked0 = "";
Those variables (checked0-7) are unused.

2017-08-09 18:48 UTC, mlamberti commented on Applications/HTTP/httpd-fs/main.js
> +			if ( val == 1 ) { json['checked0'] = "checked"; }
Make it a loop:
```
for( var i = 0; i < 8; i++; ) {
    if( json['bits'] & (1<<i) ) json['checked'+i] = "checked";
}
```

2017-08-10 09:46 UTC, cdomnik commented
Hi Michael,
habe die gewünschten Änderungen umgesetzt. Außerdem habe ich auf Wunsch von Thomas die Verzögerung des Expand Tasks auf 100ms runter gesetzt. Sollte passen mit dem Timing, hatte nur manchmal Timingprobleme, wenn ich die Webseite alle 100ms neu aufbaue.
Gruß, Christoph

2017-08-10 11:26 UTC, merged